#!/usr/bin/env bash

##
# Use this to echo docker container stats on memory and cpu usage.
#
# Author: Gary Crawford
##

set -o errexit
set -o nounset

if [[ $# -eq 0 ]] ; then
  echo 'container id is required'
  exit 1
fi

container_id="$1"

MEM=/sys/fs/cgroup/memory/docker/${container_id}
CPU=/sys/fs/cgroup/cpuacct/docker/${container_id}
BIO=/sys/fs/cgroup/blkio/docker/${container_id}

cat ${MEM}/memory.stat | while read name value; do
  echo "koomus.bulk-loader.memory.stat.${name} ${value}"
done

echo "koomus.bulk-loader.memory.max_usage_in_bytes $(cat ${MEM}/memory.max_usage_in_bytes)"
echo "koomus.bulk-loader.memory.usage_in_bytes $(cat ${MEM}/memory.usage_in_bytes)"

cat ${CPU}/cpuacct.stat | while read name value; do
  echo "koomus.bulk-loader.cpuacct.stat.${name} ${value}"
done

echo "koomus.bulk-loader.cpuacct.cpuacct.usage $(cat ${CPU}/cpuacct.usage)"
echo "koomus.bulk-loader.blkio.blkio.io_service_bytes $(cat ${BIO}/blkio.io_service_bytes)"

exit 0
